### ISSUE TITLE
Problems with the Dockerfile.multistage

### ISSUE THREAD

**Issue by kalilmvp** [nebrass/playing-with-quarkus-monolith-book-code#30]
Hi @nebrass , looking at the version of the Dockerfile that you´ve presented on the book and that is pushed on this repo, it´s contents are:

```
FROM quay.io/quarkus/centos-quarkus-maven:20.1.0-java11 AS build
COPY pom.xml /usr/src/app/
RUN mvn -f /usr/src/app/pom.xml -B de.qaware.maven:go-offline-maven-plugin:1.2.5:resolve-dependencies
COPY src /usr/src/app/src
USER root
RUN chown -R quarkus /usr/src/app
USER quarkus
RUN mvn -f /usr/src/app/pom.xml -Pnative clean package -DskipTests -DskipITs

FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY --from=build /usr/src/app/target/*-runner /work/application

RUN chmod 775 /work /work/application \
  && chown -R 1001 /work \
  && chmod -R "g+rwX" /work \
  && chown -R 1001:root /work

EXPOSE 8080
USER 1001

CMD echo "The application will start in 10s..." && sleep 10 && ./application -Dquarkus.http.host=0.0.0.0
```

In the beginning, the COPY pom.xml .... does not work, the error is:

```
COPY failed: stat /var/lib/docker/tmp/docker-builder205176569/pom.xml: no such file or directory
##[error]COPY failed: stat /var/lib/docker/tmp/docker-builder205176569/pom.xml: no such file or directory
##[error]The process '/usr/bin/docker' failed with exit code 1
```

It happened locally and now that i tried to deploy at Azure Devops the same error persists. Do you know what´s wrong? It seems related to the build context path, but i wasn´t able to solve it yet.

**Comment by kalilmvp** [comment]
I discovered what the problem was and the solution was here:

[https://github.com/quarkusio/quarkus/issues/10132#issuecomment-646963937](url)

All files were being ignored on the **.dockerignore** file, except the artifacts. Adding also the pom.xml solved it:

`
*
!pom.xml
!target/*-runner
!target/*-runner.jar
!target/lib/*
!target/quarkus-app/*
`

But checking your codebase it doesn´t have it so i´m not sure how you make it work.

**Comment by nebrass** [comment]
Hello @kalilmvp,

The `.dockerignore` file is already in the repository: https://github.com/nebrass/playing-with-quarkus-monolith-book-code/blob/master/.dockerignore

I don't have any special configuration - here's the **Azure Devops Build task** I'm using:

```
- task: Docker@2
  displayName: 'Docker Multistage Build'
  inputs:
    containerRegistry: 'nebrass@DockerHub'
    repository: 'nebrass/quarkushop-monolithic-application'
    command: 'build'
    Dockerfile: '**/Dockerfile.multistage'
    buildContext: '.'
    tags: |
      $(Build.BuildId)
      latest
```
